### PR TITLE
fix: Why not set tenant to "" in ListTasksParams$Builder?

### LINKED ISSUE #653: Why not set tenant to "" in ListTasksParams$Builder?
Hi, I found that in ListTasksParams$Builder, the tenant field is required to be nonNull.

https://github.com/a2aproject/a2a-java/blob/7bf82c694a33ef8538c73db23d7aa42e84da3abb/spec/src/main/java/io/a2a/spec/ListTasksParams.java#L230

Whereas in MessageSendParams, the builder sets the tenant field to "" if it is null.

https://github.com/a2aproject/a2a-java/blob/7bf82c694a33ef8538c73db23d7aa42e84da3abb/spec/src/main/java/io/a2a/spec/MessageSendParams.java#L134

Why the difference? 

Considering that the constructors of ListTasksParams also set the tenant field to "" when it is not specified, would it be possible to do the same for ListTasksParams$Builder as well?

Thanks!

### PR DESCRIPTION
**Pull request by ehsavoie**
ListTasksParams.Builder should set the tenant to "" when it is not defined.

Fixes #653 🦕

### CODE REVIEW

**Review by jmesnil — APPROVED** [review]

File: spec/src/main/java/io/a2a/spec/DeleteTaskPushNotificationConfigParams.java [hunk 1]
```diff
@@ -111,7 +111,7 @@ public DeleteTaskPushNotificationConfigParams build() {
             return new DeleteTaskPushNotificationConfigParams(
                     Assert.checkNotNullParam("id", id),
                     Assert.checkNotNullParam("pushNotificationConfigId", pushNotificationConfigId),
-                    Assert.checkNotNullParam("tenant", tenant));
+                    tenant != null ? tenant : "");
```
Comment (kabir) [inline spec/src/main/java/io/a2a/spec/DeleteTaskPushNotificationConfigParams.java]: Not sure if it really is needed, but we have the `io.a2a.util.Utils.defaultIfNull()` util to help with this here and other places

**Review by kabir — COMMENTED** [review]
Looks good. Just wondering if we should use the util

**Review by kabir — APPROVED** [review]
