### PR TITLE
fix: duplication of parameters in json for defining subtypes.

### LINKED ISSUE #234: [Bug]: a2a request body: multiple duplicate "kind" values appear after serialization
### What happened?

When Jackson serializes a class that implements multiple interfaces:
The getKind() method defined for each interface will be regarded as an independent attribute source by Jackson.
Both the `EventKind `and `StreamingEventKind `interfaces define the getKind() method. This is the fundamental reason for the occurrence of duplicate kind attributes during serialization.

### Relevant log output

```shell
{"kind":"message","role":"user","parts":[{"kind":"text","text":"please help me plan the route from Tian'anmen Square to Beijing West Railway Station","kind":"text"}],"messageId":"68a29ed35be55049f4350d07","contextId":"1755485011723f65lx3qvj","metadata":{"userId":"4b1fecf5-ee6a-4e1f-a122-75f5206e96fb"},"kind":"message"}
In the above report, the word "kind":"text"/"message" was repeated twice.
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by xumk**
fixed #234 fix kind dublicate because classes have gatKind method and add correctly JsonTypeName for type

### CODE REVIEW

**Comment by fjuma** [comment]
@xumk Thanks for the PR! It looks like there are some test failures related to the change.

**Comment by xumk** [comment]
@fjuma yes. i fixed it

**Comment by fjuma** [comment]
@xumk It would be good to add tests for this change.

**Comment by xumk** [comment]
@fjuma I'll try to do it soon.

**Comment by xumk** [comment]
@fjuma Hi, I added the tests.

File: spec/src/main/java/io/a2a/spec/DataPart.java [hunk 1]
```diff
@@ -6,11 +6,13 @@
 import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
 import com.fasterxml.jackson.annotation.JsonInclude;
 import com.fasterxml.jackson.annotation.JsonProperty;
+import com.fasterxml.jackson.annotation.JsonTypeName;
 import io.a2a.util.Assert;
 
 /**
  * Represents a structured data segment (e.g., JSON) within a message or artifact.
  */
+@JsonTypeName("data")
```
Comment (fjuma) [inline spec/src/main/java/io/a2a/spec/DataPart.java]: Would be good to use a constant here and then update the other places that use "data" to also use the constant.

File: spec/src/main/java/io/a2a/spec/FilePart.java [hunk 2]
```diff
@@ -6,12 +6,14 @@
...
 import com.fasterxml.jackson.annotation.JsonInclude;
 import com.fasterxml.jackson.annotation.JsonProperty;
+import com.fasterxml.jackson.annotation.JsonTypeName;
 import io.a2a.util.Assert;
 
 /**
  * Represents a file segment within a message or artifact. The file content can be
  * provided either directly as bytes or as a URI.
  */
+@JsonTypeName("file")
```
Comment (fjuma) [inline spec/src/main/java/io/a2a/spec/FilePart.java]: We should use a constant here.

File: spec/src/main/java/io/a2a/spec/TextPart.java [hunk 3]
```diff
@@ -6,11 +6,13 @@
 import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
 import com.fasterxml.jackson.annotation.JsonInclude;
 import com.fasterxml.jackson.annotation.JsonProperty;
+import com.fasterxml.jackson.annotation.JsonTypeName;
 import io.a2a.util.Assert;
 
 /**
  * Represents a text segment within a message or artifact.
  */
+@JsonTypeName("text")
```
Comment (fjuma) [inline spec/src/main/java/io/a2a/spec/TextPart.java]: Should use a constant here.

File: spec/src/test/java/io/a2a/spec/SingleKeyHashMap.java [hunk 4]
```diff
@@ -0,0 +1,14 @@
+package io.a2a.spec;
+
+import java.util.HashMap;
+
+public class SingleKeyHashMap <K, V> extends HashMap<K, V> {
```
Comment (fjuma) [inline spec/src/test/java/io/a2a/spec/SingleKeyHashMap.java]: Very minor, this could probably be a static class in the test class.

**Comment by xumk** [comment]
@fjuma i added it

File: spec/src/main/java/io/a2a/spec/Part.java [hunk 5]
```diff
@@ -12,7 +12,7 @@
  */
 @JsonTypeInfo(
```
Comment (fjuma) [inline spec/src/main/java/io/a2a/spec/Part.java:13]: I think this class can now be updated to make use of the newly introduced constants.

Comment (xumk) [reply spec/src/main/java/io/a2a/spec/Part.java:13]: sorry. I overlooked it. I Added it

Comment (fjuma) [reply spec/src/main/java/io/a2a/spec/Part.java:13]: Thanks!
