### PR TITLE
fix!: rewrite PartTypeAdapter to use flat JSON format for Part serialization

### LINKED ISSUE #689: [Bug]: RestHandler#sendMessage returns part with both "text" and "filename" fields
### What happened?

Hello!
I am currently using Alpha3 and ran into this problem:

I called RestHandler#sendMessage and expected to create a task with one TextPart.
But we get a part object like this:

```json
{
  "tasks": [
  {
    "xxx": "xxx",
    "parts": [
      {
        "text": "abc",
        "metadata": {},
        "filename": "",
        "mediaType": ""
      }
    ]
  }
]
}
```

I believe the filename field is not supposed to be there.

I also found RestHandler use grpc models/functions internally, which might be the problem: when it performs proto deserialization, it added the filename to the part model.

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ehsavoie**
Replace the nested "file" wrapper with flat fields (raw, url, filename, mediaType) aligned with the proto Part message schema and A2A spec.

Fixes #689 🦕

### CODE REVIEW

File: spec-grpc/src/test/java/io/a2a/grpc/utils/PartTypeAdapterTest.java [hunk 1]
```diff
@@ -0,0 +1,289 @@
...
+        String json = JsonFormat.printer().alwaysPrintFieldsWithNoPresence().omittingInsignificantWhitespace().print(builder);
+        Part<?> part = JsonUtil.fromJson(json, Part.class);
+        assertInstanceOf(FilePart.class, part);
+        FilePart filePart = (FilePart) part;
+        assertInstanceOf(FileWithBytes.class, filePart.file());
+        FileWithBytes fileWithBytes = (FileWithBytes) filePart.file();
+        assertEquals("image/png", fileWithBytes.mimeType());
+        assertEquals("diagram.png", fileWithBytes.name());
+        // Proto's JsonFormat encodes bytes as canonical base64 (zero trailing-padding bits),
+        // so "abc123==" (non-canonical) becomes "abc12w==" after the proto roundtrip.
```
Comment (jmesnil) [inline spec-grpc/src/test/java/io/a2a/grpc/utils/PartTypeAdapterTest.java]: what's that comment about? The builder passes `abc12w==` and I don't see `abc123==` in the test?

**Review by jmesnil — COMMENTED** [review]
When I look at the test, I wonder if we should improve the `FileWithBytes` class to take in parameter a `java.io.File` and handles the Base64 conversion from the file's bytes internally?
That'd make for a much simpler UX. wdyt?

File: spec-grpc/src/test/java/io/a2a/grpc/utils/PartTypeAdapterTest.java (hunk 1 above)
Comment (ehsavoie) [reply spec-grpc/src/test/java/io/a2a/grpc/utils/PartTypeAdapterTest.java]: yes, the issue was that abc123== was some 'wrong' base64 text that was translated to abc12w== due to padding

Comment (ehsavoie) [reply spec-grpc/src/test/java/io/a2a/grpc/utils/PartTypeAdapterTest.java]: I changed the content but forgot to remove the comment

**Comment by ehsavoie** [comment]
I've created https://github.com/a2aproject/a2a-java/issues/702 to track your suggestion
