### PR TITLE
fix: Wait for agent completion and ensure all events processed in blo…

### LINKED ISSUE #428: [Bug]: DefaultRequestHandler does not block until final state when blocking=true
## Description
version: v0.3.0.Final, v0.3.1.Final

When calling DefaultRequestHandler.onMessageSend with blocking=true, it is expected that the handler waits for the final state result before returning the response.
However, according to the test case below, the first message is returned immediately, and the remaining messages are processed in the background:

🔗 [DefaultRequestHandlerTest.java#L504](https://github.com/a2aproject/a2a-java/blob/5031b8faba7b78bbd508a3d21a6b1940ecf19013/server-common/src/test/java/io/a2a/server/requesthandlers/DefaultRequestHandlerTest.java#L504)

This behavior seems indistinguishable from the blocking=false case.

## Background

I understand that ResultAggregator was modified to run subscription logic on a background thread to prevent blocking the Vert.x worker thread, as indicated by the following comment:

// CRITICAL: The subscription itself must run on a background thread to avoid blocking
// the Vert.x worker thread. EventConsumer.consumeAll() starts a polling loop that
// blocks in dequeueEventItem(), so we must subscribe from a background thread.
// Use the @Internal executor (not ForkJoinPool.commonPool) to avoid saturation

🔗 [ResultAggregator.java#L121-L125](https://github.com/a2aproject/a2a-java/blob/5031b8faba7b78bbd508a3d21a6b1940ecf19013/server-common/src/main/java/io/a2a/server/tasks/ResultAggregator.java#L121-L125)

However, for requests where blocking=true, it is still expected that the DefaultRequestHandler waits for background task completion and returns the final aggregated result.

Currently, even though cleanupProducer calls bothComplete.join(), the handler does not appear to wait as intended.

🔗 [DefaultRequestHandler.java#L607](https://github.com/a2aproject/a2a-java/blob/5031b8faba7b78bbd508a3d21a6b1940ecf19013/server-common/src/main/java/io/a2a/server/requesthandlers/DefaultRequestHandler.java#L607)

## Expected Behavior

When blocking=true, DefaultRequestHandler should:

Wait for all background tasks to complete (including final state aggregation).

Return the final response only after all events have been processed.

## Actual Behavior

The first message is returned immediately.

Remaining events are processed asynchronously in the background.

Behavior is effectively identical to blocking=false.

## Request

Please review the intended behavior for blocking=true requests and confirm whether the current implementation aligns with the design goals.
If not, it may require ensuring that bothComplete.join() properly waits for all background processing before returning the response.

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by kabir**
…cking calls

Fixes race condition where DefaultRequestHandler.onMessageSend() returns before all task events are fully processed and persisted to TaskStore, resulting in incomplete Task objects being returned to clients (missing artifacts, incorrect state).

Root Cause:
- Blocking calls interrupted immediately after first event and returned to client before background event consumption completed
- Agent execution and event processing happened asynchronously in background
- No synchronization to ensure all events were consumed and persisted before returning Task to client

Solution (4-step process):
1. Wait for agent to finish enqueueing events (configurable timeout)
2. Close the queue to signal consumption can complete (breaks dependency)
3. Wait for consumption to finish processing events (configurable timeout)
4. Fetch final task state from TaskStore (has all artifacts and correct state)

This ensures blocking calls return complete Task objects with all artifacts and correct state, including support for fire-and-forget tasks that never emit final state events.

Added unit tests:
- testBlockingFireAndForgetReturnsNonFinalTask: Validates fire-and-forget pattern
- testBlockingCallReturnsCompleteTaskWithArtifacts: Ensures all artifacts included

Fixes #428 🦕

### CODE REVIEW

**Comment by kabir** [comment]
@flex-myeonghyeon I moved the work here

~Note that for some reason, GitHub isn't showing the code I have locally, so if you want to check you might have to pull down the branch.~ This was my IDE not behaving. It should be the same now :-)

**Comment by kabir** [comment]
Replaces #430

File: server-common/src/main/java/io/a2a/server/requesthandlers/DefaultRequestHandler.java [hunk 1]
```diff
@@ -210,7 +214,63 @@ public EventKind onMessageSend(MessageSendParams params, ServerCallContext conte
...
+                        LOGGER.debug("Consumption completed for task {}", taskId);
+                    }
+                } catch (InterruptedException e) {
+                    Thread.currentThread().interrupt();
+                    LOGGER.warn("Interrupted waiting for task {} completion", taskId, e);
+                } catch (java.util.concurrent.ExecutionException e) {
+                    LOGGER.warn("Error during task {} execution", taskId, e.getCause());
+                } catch (java.util.concurrent.TimeoutException e) {
+                    LOGGER.warn("Timeout waiting for consumption to complete for task {}", taskId);
+                }
```
[the remark this answers is not in the document]
Comment (kabir) [reply server-common/src/main/java/io/a2a/server/requesthandlers/DefaultRequestHandler.java:302]: Fixed

File: server-common/src/main/java/io/a2a/server/requesthandlers/DefaultRequestHandler.java [hunk 2]
```diff
@@ -63,6 +63,8 @@
 public class DefaultRequestHandler implements RequestHandler {
 
     private static final Logger LOGGER = LoggerFactory.getLogger(DefaultRequestHandler.class);
+    private static final int AGENT_COMPLETION_TIMEOUT_SECONDS = 5;
+    private static final int CONSUMPTION_COMPLETION_TIMEOUT_SECONDS = 2;
```
Comment (flex-myeonghyeon) [inline server-common/src/main/java/io/a2a/server/requesthandlers/DefaultRequestHandler.java]: In some cases, a longer wait time might be necessary.
Would it be possible to make this configurable — for example, by passing it as a parameter or injecting it through the DefaultRequestHandler constructor?

Comment (kabir) [reply server-common/src/main/java/io/a2a/server/requesthandlers/DefaultRequestHandler.java]: @flex-myeonghyeon Good idea, I've added some MP Config properties

**Comment by flex-myeonghyeon** [comment]
@kabir 
Looks good to me!
Once the snapshot version is deployed and available, I’ll test it in my development environment.

File: server-common/src/main/java/io/a2a/server/requesthandlers/DefaultRequestHandler.java [hunk 3]
```diff
@@ -93,6 +115,19 @@ public DefaultRequestHandler(AgentExecutor agentExecutor, TaskStore taskStore,
...
 
+    /**
+     * For testing
+     */
+    public static DefaultRequestHandler create(AgentExecutor agentExecutor, TaskStore taskStore,
+                         QueueManager queueManager, PushNotificationConfigStore pushConfigStore,
+                         PushNotificationSender pushSender, Executor executor) {
+        DefaultRequestHandler handler =
+                new DefaultRequestHandler(agentExecutor, taskStore, queueManager, pushConfigStore, pushSender, executor);
+        handler.agentCompletionTimeoutSeconds = 5;
```
Comment (ehsavoie) [inline server-common/src/main/java/io/a2a/server/requesthandlers/DefaultRequestHandler.java:126]: Shouldn't you pass those values as parameters for testing ?
