### PR TITLE
fix: issue 226

### LINKED ISSUE #226: [Bug]:
### What happened?

A TaskStatus update message is optional. ProtoUtils.FromProto doesn't take that into account, trying to convert the update message in every stituation

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ehsavoie**
Checking if the TaskUpdate has an update message before trying to convert it.

Fixes #226 🦕

### CODE REVIEW

File: spec-grpc/src/main/java/io/a2a/grpc/utils/ProtoUtils.java [hunk 1]
```diff
@@ -822,9 +822,12 @@ private static DataPart dataPart(io.a2a.grpc.DataPart dataPart) {
         }
 
         private static TaskStatus taskStatus(io.a2a.grpc.TaskStatus taskStatus) {
-            return new TaskStatus(
-                    taskState(taskStatus.getState()),
-                    message(taskStatus.getUpdate()),
+            TaskState state = taskState(taskStatus.getState());
```
Comment (fjuma) [inline spec-grpc/src/main/java/io/a2a/grpc/utils/ProtoUtils.java:892]: Can taskStatus.getState() return null? I don't seem to see that here:

https://github.com/a2aproject/a2a-java/blob/main/spec-grpc/src/main/java/io/a2a/grpc/TaskStatus.java#L75

Let me know if I'm missing something.

Comment (fjuma) [reply spec-grpc/src/main/java/io/a2a/grpc/utils/ProtoUtils.java:892]: @ehsavoie Just bumping this question again in case you missed it.
