### PR TITLE
fix!: Update a2a.proto changes

### LINKED ISSUE #686: Upgrade a2a.proto to reflect its current status
Update the a2a.proto to commit https://github.com/a2aproject/A2A/commit/1997c9d63058ca0b89361a7d6e508f4641a6f68b

### PR DESCRIPTION
**Pull request by ehsavoie**
- Aligning to the latest version of a2a.proto
- Update tests to match a2a.proto changes:
  Fixes test failures after proto update - adjusts JSON structures and
  package references to align with new proto definitions.

Fixes #686 🦕

### CODE REVIEW

**Comment by kabir** [comment]
@ehsavoie should this have “fix!:” to show it is a breaking change?

File: transport/rest/src/main/java/io/a2a/transport/rest/handler/RestHandler.java [hunk 1]
```diff
@@ -184,7 +196,7 @@ public HTTPRestResponse subscribeToTask(ServerCallContext context, String tenant
             if (!agentCard.capabilities().streaming()) {
                 return createErrorResponse(new InvalidRequestError("Streaming is not supported by the agent"));
             }
-            TaskIdParams params = new TaskIdParams(taskId, tenant);
+            TaskIdParams params = TaskIdParams.builder().id(taskId).tenant(tenant).build();
```
Comment (jmesnil) [inline transport/rest/src/main/java/io/a2a/transport/rest/handler/RestHandler.java:190]: nit: The subscribeTask does not have a `metadata` parameter but reusing the TaskIdParams makes that confusing

File: spec/src/main/java/io/a2a/spec/TaskIdParams.java [hunk 2]
```diff
@@ -14,7 +16,7 @@
  * @param tenant optional tenant, provided as a path parameter.
  * @see <a href="https://a2a-protocol.org/latest/">A2A Protocol Specification</a>
  */
-public record TaskIdParams(String id, String tenant) {
+public record TaskIdParams(String id, String tenant, @Nullable Map<String, Object> metadata) {
```
Comment (jmesnil) [inline spec/src/main/java/io/a2a/spec/TaskIdParams.java]: the name of the class no longer seem correct. Should be `CancelTaskParams`?

File: transport/rest/src/main/java/io/a2a/transport/rest/handler/RestHandler.java [hunk 3]
```diff
@@ -144,12 +147,21 @@ public HTTPRestResponse sendStreamingMessage(ServerCallContext context, String t
...
 
-    public HTTPRestResponse cancelTask(ServerCallContext context, String tenant, String taskId) {
+    @SuppressWarnings("unchecked")
+    public HTTPRestResponse cancelTask(ServerCallContext context, String tenant, String body, String taskId) {
         try {
             if (taskId == null || taskId.isEmpty()) {
                 throw new InvalidParamsError();
             }
-            TaskIdParams params = new TaskIdParams(taskId, tenant);
+            Map<String, Object> metadata = Collections.emptyMap();
```
Comment (jmesnil) [inline transport/rest/src/main/java/io/a2a/transport/rest/handler/RestHandler.java]: Could this code be moved to a JSON utils or something already existing to cleanly handle the JSON String <-> Map conversion?

**Review by jmesnil — APPROVED** [review]
/lgtm
