### PR TITLE
fix!: Rename pushNotification to pushNotificationConfig (#286)

### LINKED ISSUE #286: [Bug]: MessageSendConfiguration::pushNotification should be pushNotificationConfig
### What happened?

The Java SDK seems to diverge from both the specification and other SDK implementations:

- Java SDK example: https://github.com/a2aproject/a2a-java/blob/ce15a4292c25e5ac91774635cad8f7944e2ccb12/spec/src/main/java/io/a2a/spec/MessageSendConfiguration.java#L16
- Python example: https://github.com/a2aproject/a2a-python/blob/675354a4149f15eb3ba4ad277ded00ad501766dd/src/a2a/types.py#L1291
- TypeScript example: https://github.com/a2aproject/a2a-js/blob/21048fb0425d27323c67a1d3d19f64f79220d689/src/types.ts#L505

I'll attach a PR shortly.

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by powmax-commits**
# Description

Thank you for opening a Pull Request!
Before submitting your PR, there are a few things you can do to make sure it goes smoothly:

- [X] Follow the [`CONTRIBUTING` Guide](../CONTRIBUTING.md).
- [X] Make your Pull Request title in the <https://www.conventionalcommits.org/> specification.
    - Important Prefixes for [release-please](https://github.com/googleapis/release-please):
        - `fix:` which represents bug fixes, and correlates to a [SemVer](https://semver.org/) patch.
        - `feat:` represents a new feature, and correlates to a SemVer minor.
        - `feat!:`, or `fix!:`, `refactor!:`, etc., which represent a breaking change (indicated by the `!`) and will result in a SemVer major.
- [x] Ensure the tests pass
- [X] Appropriate READMEs were updated (if necessary)

Fixes #286 🦕

### CODE REVIEW

File: spec-grpc/src/main/java/io/a2a/grpc/A2A.java [hunk 1]
```diff
@@ -295,200 +295,200 @@ public static void registerAllExtensions(
       "le/api/field_behavior.proto\032\033google/prot" +
       "obuf/empty.proto\032\034google/protobuf/struct" +
       ".proto\032\037google/protobuf/timestamp.proto\"" +
-      "\236\001\n\030SendMessageConfiguration\022\035\n\025accepted" +
```
Comment (fjuma) [inline spec-grpc/src/main/java/io/a2a/grpc/A2A.java:298]: We automatically generate this file using `buf generate` from the .proto specification file from the a2a repo. We can remove these changes from this PR for now and once updated upstream, we'll incorporate the changes here.

File: spec-grpc/src/main/java/io/a2a/grpc/SendMessageConfiguration.java [hunk 2]
```diff
@@ -103,42 +103,42 @@ public java.lang.String getAcceptedOutputModes(int index) {
     return acceptedOutputModes_.getByteString(index);
   }
 
-  public static final int PUSH_NOTIFICATION_FIELD_NUMBER = 2;
-  private io.a2a.grpc.PushNotificationConfig pushNotification_;
+  public static final int PUSH_NOTIFICATION_CONFIG_FIELD_NUMBER = 2;
```
Comment (fjuma) [inline spec-grpc/src/main/java/io/a2a/grpc/SendMessageConfiguration.java]: Same here, since we auto-generate this file, we can remove these changes for now.

File: spec-grpc/src/main/java/io/a2a/grpc/SendMessageConfigurationOrBuilder.java [hunk 3]
```diff
@@ -56,27 +56,27 @@ public interface SendMessageConfigurationOrBuilder extends
    * A configuration of a webhook that can be used to receive updates
    * </pre>
    *
-   * <code>.a2a.v1.PushNotificationConfig push_notification = 2;</code>
-   * @return Whether the pushNotification field is set.
+   * <code>.a2a.v1.PushNotificationConfig push_notification_config = 2;</code>
```
Comment (fjuma) [inline spec-grpc/src/main/java/io/a2a/grpc/SendMessageConfigurationOrBuilder.java]: Same here, this is an auto-generated file.

File: spec-grpc/src/main/proto/a2a.proto [hunk 4]
```diff
@@ -124,7 +124,7 @@ message SendMessageConfiguration {
   // The output modes that the agent is expected to respond with.
   repeated string accepted_output_modes = 1;
   // A configuration of a webhook that can be used to receive updates
-  PushNotificationConfig push_notification = 2;
+  PushNotificationConfig push_notification_config = 2;
```
Comment (fjuma) [inline spec-grpc/src/main/proto/a2a.proto]: Would you be able to raise an issue in https://github.com/a2aproject/A2A and submit a PR against that project with this change? (that's where we get this .proto file from and use it to generate the files).

**Review by fjuma — CHANGES_REQUESTED** [review]
Good catch, @powmax-commits!

I've just added some small comments here to remove the changes from the auto-generated gRPC files for now and submit a PR against https://github.com/a2aproject/A2A/issues to correct the gRPC .proto spec file. Once that change is included in a release, we'll update the generated files here accordingly.

Thanks very much!

**Comment by powmax-commits** [comment]
Thanks for taking a look @fjuma - I'll address both and update the request.

File: spec-grpc/src/main/proto/a2a.proto (hunk 4 above)
Comment (powmax-commits) [reply spec-grpc/src/main/proto/a2a.proto]: Pending, will backlink here.

File: spec-grpc/src/main/java/io/a2a/grpc/SendMessageConfigurationOrBuilder.java (hunk 3 above)
Comment (powmax-commits) [reply spec-grpc/src/main/java/io/a2a/grpc/SendMessageConfigurationOrBuilder.java]: Done.

File: spec-grpc/src/main/java/io/a2a/grpc/SendMessageConfiguration.java (hunk 2 above)
Comment (powmax-commits) [reply spec-grpc/src/main/java/io/a2a/grpc/SendMessageConfiguration.java]: Done.

File: spec-grpc/src/main/java/io/a2a/grpc/A2A.java (hunk 1 above)
Comment (powmax-commits) [reply spec-grpc/src/main/java/io/a2a/grpc/A2A.java:298]: Done.

File: spec-grpc/src/main/proto/a2a.proto (hunk 4 above)
Comment (powmax-commits) [reply spec-grpc/src/main/proto/a2a.proto]: Issue: https://github.com/a2aproject/A2A/issues/1091

Comment (fjuma) [reply spec-grpc/src/main/proto/a2a.proto]: Great, thanks very much!

Comment (powmax-commits) [reply spec-grpc/src/main/proto/a2a.proto]: No problem - PR here: https://github.com/a2aproject/A2A/pull/1092
